# Divide y venceras

### 1. Maximo y minimo valor de una lista

**Simple**

In [9]:
import random
arr = [random.randint(1,200) for _ in range(25)]
print(arr)

[130, 42, 30, 28, 31, 13, 190, 165, 159, 81, 73, 188, 45, 166, 179, 22, 5, 45, 72, 63, 72, 22, 5, 14, 155]


In [10]:
print(max(arr))

190


**Fuerza bruta**

In [1]:
def max_arr(arr):
  max = arr[0]
  for i in range(1, len(arr)):
    if(arr[i] > max):
      max = arr[i]
  return max

In [2]:
def min_arr(arr):
  min = arr[0]
  for i in range(1, len(arr)):
    if(arr[i] < min):
      min = arr[i]
  return min

In [3]:
import random

def main():
  arr = list(range(30)) #Genera elementos consecutivos [0,1,2,...,29] de una lista

  random.shuffle(arr)   #Barajar la secuencia
  print("Arreglo: ", arr)

  print("Minimo: ", min_arr(arr))
  print("Maximo: ", max_arr(arr))

main()

Arreglo:  [12, 9, 0, 13, 17, 18, 7, 3, 14, 21, 23, 22, 6, 27, 20, 4, 8, 26, 28, 15, 2, 29, 5, 25, 24, 19, 10, 1, 11, 16]
Minimo:  0
Maximo:  29


**Divide y venceras** sol1

In [6]:
def obtenerMax(arr, i, j):
  if i == j:
    return arr[i]

  medio = (i+j) // 2
  maxi = obtenerMax(arr, i, medio)
  maxd = obtenerMax(arr, medio + 1, j)
  return maxi if maxi > maxd else maxd


def obtenerMin(arr, i, j):
  if i == j:
    return arr[i]

  medio = (i+j) // 2
  mini = obtenerMin(arr, i, medio)
  mind = obtenerMin(arr, medio + 1, j)
  return mini if mini < mind else mind 

In [5]:
import random

def main():
  arr = [random.randint(1,200) for x in range(25)]
  print(arr)

  print("El minimo valor en el arreglo es: ", obtenerMin(arr, 0, len(arr)-1))
  print("El maximo valor en el arreglo es: ", obtenerMax(arr, 0, len(arr)-1))

main()

[198, 67, 66, 145, 111, 3, 103, 23, 102, 8, 40, 71, 59, 4, 71, 129, 153, 119, 139, 106, 99, 109, 106, 93, 137]
El minimo valor en el arreglo es:  3
El maximo valor en el arreglo es:  198


In [9]:
def max(lst, i, d):
    if i==d:
        return lst[i]
    
    mid = (int)((i+d)//2)
    sub1 = max(lst, i, mid)
    sub2= max(lst, mid+1, d)
    
    if(sub1>=sub2): return sub1
    else: return sub2
    
    
import random
arr = [random.randint(1,200) for x in range(10)]
print(arr)
print(max(arr, 0, len(arr)-1))

[4, 193, 186, 196, 106, 33, 28, 165, 13, 105]
196


**Divide y venceras** sol2

In [7]:
def divideAndConquer_Max(arr, ind, len):
    maximum = -1;

    if (ind >= len - 2):  #Si llegamos el penultimo indice
        if (arr[ind] > arr[ind + 1]):
            return arr[ind];
        else:
            return arr[ind + 1];

    maximum = divideAndConquer_Max(arr, ind + 1, len);

    if (arr[ind] > maximum):
        return arr[ind];
    else:
        return maximum;


def divideAndConquer_Min(arr, ind, len):
    minimum = 0;
    if (ind >= len - 2):  #Si llegamos el penultimo indice
        if (arr[ind] < arr[ind + 1]):
            return arr[ind];
        else:
            return arr[ind + 1];

    minimum = divideAndConquer_Min(arr, ind + 1, len);

    if (arr[ind] < minimum):
        return arr[ind];
    else:
        return minimum;

In [8]:
def main():
  minimum, maximum = 0, -1;

  # Inicializamos el arreglo
  arr = [6, 4, 8, 90, 12, 56, 7, 1, 63];

  maximum = divideAndConquer_Max(arr, 0, 9);
  minimum = divideAndConquer_Min(arr, 0, 9);

  print("El minimo numero en el arreglo es: ", minimum);
  print("El maximo numero en el arreglo es: ", maximum);

main()

El minimo numero en el arreglo es:  1
El maximo numero en el arreglo es:  90


### 2. Multiplicacion enteros

In [18]:
def mult(a, b, n):
  if n == 1:
    return a * b
  
  # operator //: divide y redondea al entero más próximo
  ai = a // 10**(n//2)  # Numero ai de la izquierda de n/2 digitos 
  ad = a % 10**(n//2)   # Numero ad de la derecha de n/2 digitos
  bi = b // 10**(n//2)  # Numero bi de la izquierda de n/2 digitos 
  bd = b % 10**(n//2)   # Numero bd de la derecha de n/2 digitos 

  z1 = mult(ai, bi, n//2) * 10**n
  z2 = (mult(ai, bd, n//2) + mult(ad, bi, n//2)) * 10**(n//2)
  z3 = mult(ad, bd, n//2)
  
  return z1 + z2 + z3



In [20]:
def main():
  a = 1234
  b = 5678
  n = 16  # n=9 es válido; sin embargo n=16 mejora la precision del calculo
  res = mult(a, b, n)
  assert res == a * b # bool. Compara si el resultado de la función es igual al producto de a*b
  res == a * b
  print(res)

main()


7006652


### 3. Multiplicacion matrices

In [1]:
def mul_mat(a, b, c, i, ii, j, jj):
  if i == ii: #i=indice inicial, ii:indice final:len
    temp = 0
    for k in range(len(a)):
      temp += a[i][k] * b[k][j]
    c[i][j] = temp
  else:
    imid = (i + ii) // 2
    jmid = (j + jj) // 2
    mul_mat(a, b, c,        i, imid,        j, jmid)
    mul_mat(a, b, c, imid + 1,   ii,        j, jmid)
    mul_mat(a, b, c,        i, imid, jmid + 1, jj)
    mul_mat(a, b, c, imid + 1,   ii, jmid + 1, jj)


In [2]:
import numpy as np

def main():
  a = np.random.randint(10, size=(8, 8))  #Genera valores [0,9] en una matriz de 8*8
  b = np.random.randint(10, size=(8, 8))  #Genera valores [0,9] en una matriz de 8*8
  print("Matriz A: "); print(a)
  print("Matriz B: "); print(b)
  c = np.zeros((8, 8))  #Retorna una Matriz de 8*8 rellena de ceros
  mul_mat(a, b, c, 0, len(a) - 1, 0, len(a) - 1)  #len(matriz) retorna el tamaño de la dimension, 8 en este caso
  assert (c == np.matmul(a, b)).all()
  print("\nMatriz C = A x B: ")
  print(c)

main()

Matriz A: 
[[4 9 3 5 6 0 4 1]
 [8 5 9 1 8 5 9 1]
 [4 0 7 6 1 2 8 1]
 [8 9 8 4 3 2 1 8]
 [9 7 4 9 5 2 7 7]
 [8 6 1 7 6 6 8 8]
 [8 0 4 8 5 6 7 0]
 [5 6 6 9 9 3 9 2]]
Matriz B: 
[[6 8 3 6 3 2 7 4]
 [1 8 4 4 7 5 6 6]
 [0 2 5 8 4 9 3 2]
 [0 7 7 0 3 8 8 8]
 [7 7 7 5 3 7 5 5]
 [2 7 9 3 2 3 0 8]
 [8 1 1 9 4 3 7 0]
 [8 7 5 5 4 6 5 6]]

Matriz C = A x B: 
[[115. 198. 149. 155. 140. 180. 194. 152.]
 [199. 236. 211. 281. 172. 234. 229. 174.]
 [107. 124. 127. 168. 101. 162. 163. 105.]
 [154. 272. 208. 218. 180. 243. 228. 213.]
 [212. 304. 233. 243. 194. 265. 298. 241.]
 [236. 311. 246. 240. 185. 243. 277. 252.]
 [151. 212. 196. 186. 119. 190. 206. 177.]
 [193. 270. 241. 247. 185. 277. 279. 221.]]


### 4. Suma de valores de una lista

In [12]:
import random

def sumarize(a, i, f):
  if i == f:
    return a[i]
  else:
    mid = (i + f) // 2
    s1 = sumarize(a, i, mid)
    s2 = sumarize(a, mid + 1, f)
    return s1 + s2

def main():
  arr = list(range(5)) #Genera elementos ordenados [0,1,2,...,29] 
  #print(arr)          
  random.shuffle(arr)   #Barajar la secuencia
  print("Arreglo: ", arr)
  
  print("Suma: ", sumarize(arr, 0, len(arr) - 1))

main()


Arreglo:  [3, 0, 1, 4, 2]
Suma:  10


In [14]:
import random

def sum1(lst):
    if len(lst)==1:
        return lst[0]
    
    mid = (int)(len(lst)/2)
    sub1 = lst[:mid]
    sub2 = lst[mid:]
    
    return sum1(sub1) + sum1(sub2)
    
    
arr = [random.randint(1,100) for x in range(5)]
print(arr)
print(sum1(arr))



[83, 8, 89, 30, 10]
220


In [15]:
def sum2(lst, i, d):
    if i==d:
        return lst[i]
    
    mid = (int)((i+d)//2)
    sub1 = sum2(lst, i, mid)
    sub2= sum2(lst, mid+1, d)
    
    return sub1 + sub2
    
    
import random
arr = [random.randint(1,200) for x in range(5)]
print(arr)
print(sum2(arr, 0, len(arr)-1))

[187, 98, 33, 77, 183]
578


### Multiplicacion de elementos de una lista

In [17]:
def multpl(lst, i, d):
    if i==d:
        return lst[i]
    
    mid = (int)((i+d)//2)
    sub1 = multpl(lst, i, mid)
    sub2= multpl(lst, mid+1, d)
    
    return sub1 * sub2
    
    
import random
arr = [random.randint(1,200) for x in range(3)]
print(arr)
print(multpl(arr, 0, len(arr)-1))

[107, 6, 101]
64842


### Dado dos arrays, indica si son iguales

In [15]:
def iguales(lst1, lst2, i, d):
    if(i==d):
        print(lst1[i], " ", lst2[i])
        if(lst1[i]==lst2[i]):
            return -1
        else:
            return i
    
    mid = (int)((i+d)/2)
    sub1 = iguales(lst1, lst2, i, mid)
    sub2= iguales(lst1, lst2, mid+1, d)
    
    if(sub1 != -1): 
        return sub1
    if(sub2 != -1): 
        return sub2
    
    return -1


import random
arr1 = [7,8,8,8,7]
arr2 = [7,7,7,7,7]
print("Arreglo 1: ", arr1)
print("Arreglo 2: ", arr2)
if(iguales(arr1, arr2, 0, len(arr1)-1)== -1): print("Son iguales")
else: print("No son iguales")

Arreglo 1:  [7, 8, 8, 8, 7]
Arreglo 2:  [7, 7, 7, 7, 7]
7   7
8   7
8   7
8   7
7   7
No son iguales


### Media

In [19]:
def media(lst, i, d):
    if i==d:
        return lst[i]
    
    mid = (int)((i+d)/2)
    sub1 = media(lst, i, mid)
    sub2= media(lst, mid+1, d)
    
    return sub1 + sub2
    
    
import random
arr = [random.randint(1,200) for x in range(5)]
print(arr)
print(media(arr, 0, len(arr)-1)/5)

[84, 188, 18, 93, 91]
94.8


### CONTADOR DE PALABRAS

In [1]:
texto = '''Bienvenidos alumnos al curso de Complejidad Algoritmica
Las competencias del curso son:
Competencia General: Razonamiento Cuantitativo de nivel 1 para Ingeniería de software y nivel 2 para Ciencias de computación
Competencia Específica de Responsabilidad Etica y Profesional de nivel 1 para Ciencias de Computación e Ingeniería de Software.'''

print (texto)
    
palabras = texto.split()
cont=0
while (cont < len(palabras)):
    palabra = palabras[cont]
    cont = cont + 1

print("Numero de Palabras", cont)

Bienvenidos alumnos al curso de Complejidad Algoritmica
Las competencias del curso son:
Competencia General: Razonamiento Cuantitativo de nivel 1 para Ingeniería de software y nivel 2 para Ciencias de computación
Competencia Específica de Responsabilidad Etica y Profesional de nivel 1 para Ciencias de Computación e Ingeniería de Software.
Numero de Palabras 48


In [3]:
def ContPalabrasDC(palabras):
    if (len(palabras) == 1):
        return 1
    count = len(palabras)
    sub1 = ContPalabrasDC(palabras[0:count//2])
    sub2 =ContPalabrasDC(palabras[count//2:])
    
    return sub1 + sub2
        


def main():
  texto = '''Bienvenidos alumnos al curso de Complejidad Algoritmica
  Las competencias del curso son:
  Competencia General: Razonamiento Cuantitativo de nivel 1 para Ingeniería de software y nivel 2 para Ciencias de computación
  Competencia Específica de Responsabilidad Etica y Profesional de nivel 1 para Ciencias de Computación e Ingeniería de Software.'''

  print (texto)

  palabras = texto.split()
  cont = ContPalabrasDC(palabras)
  print("Numero de Palabras DC: ", cont)

main()

Bienvenidos alumnos al curso de Complejidad Algoritmica
  Las competencias del curso son:
  Competencia General: Razonamiento Cuantitativo de nivel 1 para Ingeniería de software y nivel 2 para Ciencias de computación
  Competencia Específica de Responsabilidad Etica y Profesional de nivel 1 para Ciencias de Computación e Ingeniería de Software.
Numero de Palabras DC:  48
