In [20]:
import heapq as hq
import numpy as np
import graphviz as gv
import math
from collections import defaultdict

## PARTE I
(4 puntos)

### PREGUNTA 1
Implemente una variación del algoritmo DFS, al que llamaremos RDFS, en el que se deberán accedera los vecinos de cada nodo de manera aleatoria. 
Por ejemplo dado el grafo siguiente en lista deadyacencia:
- 0: 1, 5
- 1: 0, 2, 3
- 2: 1, 3, 4
- 3: 1, 2, 5
- 4: 2, 5
- 5: 0, 3, 4

El DFS tradicional iniciado desde el nodo cero siempre recorrerá primero al 1 y luego al 5, desde el 1,intentará ir al 0 (que ya está visitado) luego al 2 y luego al 3 y así sucesivamente.

Lo que se le pide es que si ejecutamos el algoritmo solicitado RDFS, partiendo del nodo 0, podría irprimero al nodo 5 antes que al 1, y en otra ocasión podría ir al 1 y luego al 5, etc.

Elabore 3 grafos distintos y realice varias ejecuciones donde se debe mostrar que los resultados son distintos cada vez.

# DFS

In [90]:
### DFS: RECORRIDO EN PROFUNDIDAD - NORMAL

import random
def DFS(primer_nodo, grafo):
    visitados = []
    pila = [primer_nodo]
    while pila:
        nodo = pila.pop()
        
        if nodo not in visitados:
            visitados.append(nodo)
            for nodo_hijo in grafo[nodo]:
                pila.append(nodo_hijo)
        
    return visitados


In [91]:
### DFS: RECORRIDO EN PROFUNDIDAD - RDFS

import random
def RDFS(primer_nodo, grafo):
    visitados = []
    pila = [primer_nodo]
    while pila:
        nodo = pila.pop()
        
        if nodo not in visitados:
            visitados.append(nodo)
            
            temp = []
            for nodo_hijo in grafo[nodo]:
                temp.append(nodo_hijo)
            
            while temp:
                n = random.randint(0,len(temp)-1)
                pila.append(temp[n])
                del temp[n]

        
    return visitados


In [92]:
grafo1 = {
    1: [2, 3, 4],
    2: [5],
    3: [5],
    4: [],
    5: [6, 7],
    6: [],
    7: [3],
}
RDFS(1, grafo1)

[1, 4, 2, 5, 7, 3, 6]

In [93]:
grafo2 = {
  0 : [1, 5],
  1 : [0, 2, 3],
  2 : [1, 3, 4],
  3 : [1, 2, 5],
  4 : [2, 5],
  5 : [0, 3, 4]
}

RDFS(0, grafo2)

[0, 1, 2, 4, 5, 3]

In [94]:
grafo3 = {
  6 : [1, 3],
  1 : [0, 2, 3],
  2 : [1, 3, 4],
  0 : [1, 2, 6],
  4 : [2, 6],
  3 : [0, 4]
}

RDFS(0, grafo3)

[0, 6, 1, 2, 3, 4]

### PREGUNTA 2
(8 puntos)

Usted acaba de terminar una maestría en el MIT y ha decidido salir con sus amigos. Usted ha

desarrollado algunos hábitos extraños y por ello ha decidido celebrar éste momento tan importante

en su vida tomando muchos jugos tropicales. Usted empieza a tomar bebidas con bajo contenido de

azúcar como jugo de melón, luego algo más dulce como jugo de manzana hasta que no hayan más

bebidas disponibles. Una vez que empieza a tomar jugo de manzana, ya no tomará más jugo de

melón de tal forma que el contenido de azúcar no disminuye con el transcurrir del tiempo.

Siendo el aplicado discípulo de su docente de complejidad algorítmica, decide utilizar python para

decidir en qué orden tomar las bebidas según sus propias reglas.


**Input**

Cada caso de prueba empieza con N, el número de bebidas disponibles, Luego siguen N líneas con los

nombres de cada bebida, los nombres no tienen espacios en blanco. Luego sigue M, y luego M líneas

de la forma B1 B2 indicando que la bebida B2 tiene más azúcar que la bebida 1. De modo que usted

puede tomar la bebida B1 antes de empezar a tomar la B2. Asegúrese que la relación es transitiva, de

modo que hay una relación B2 B3, B1 debe tomarse antes que B3. Hay una línea en blanco al final de

cada caso de prueba. En caso de no relación entre las bebidas, Usted puede tomar aquella que

aparezca primero en el Input.

**Output**

Por cada caso de prueba usted puede imprimir el mensaje ‘caso #C: usted debería tomar las bebidas

en éste orden: B1 B2 Bn.’, donde C es el número de … caso empezando desde 1 y B1, B2 y Bn son las

bebidas de modo que el contenido de azúcar de Bi+1 es mayor o igual al contenido de Bi. Luego de

cada caso de prueba se debe imprimir una línea en blanco.


In [ ]:
'''
Ejemplo de Input
3
platano
acai
manzana
2
acai platano
manzana acai


5
acai
manzana
cereza
melon
papaya
6
manzana papaya
melon manzana
melon cereza
manzana cereza
manzana acai
acai papaya

10
papaya
cereza
melon
mango
cocona
acai
platano
manzana
capuli
durazno
11
manzana cocona
melon durazno
cereza papaya
platano mango
melon capuli
cereza durazno
acai cocona
melon manzana
manzana cereza
acai platano
manzana mango
'''

**Ejemplo de output**

Caso #1: usted debería toma*r las bebidas en éste orden: manzana acai platano.

Caso #2: usted debería tomar las bebidas en éste orden: melon manzana acai cereza papaya.

Caso #3: usted debería tomar las bebidas en éste orden: melon acai platano manzana cereza
papaya mango cocona capuli durazno.


# BFS

In [2]:
## BFS (RECORRIDO EN AMPLITUD O ANCHURA) - NORMAL

visitados = [] # List for visited nodes.
cola = []     #Initialize a queue

def bfs(visitados, grafo, nodo): #function for BFS
  visitados.append(nodo)
  cola.append(nodo)

  while cola:          # Creating loop to visit each node
    m = cola.pop(0) 
    print (m, end = " ") 

    for nodo_adyacente in grafo[m]:
      if nodo_adyacente not in visitados:
        visitados.append(nodo_adyacente)
        cola.append(nodo_adyacente)

In [36]:
## BFS (RECORRIDO EN AMPLITUD O ANCHURA) - DE ESTE PROBLEMA DE FRUTA

visitados = [] # List for visited nodes.
cola = []     #Initialize a queue

def bfsFrutas(visitados, grafo, nodo): #function for BFS
  visitados.append(nodo)
  cola.append(nodo)

  while cola:          # Creating loop to visit each node
    m = cola.pop(0) 
    print (m, end = " ") 
        
    temp=[]
    for nodo_adyacente in grafo[m]:
      if nodo_adyacente not in visitados:
        temp.append(nodo_adyacente)
    
    cont = 0
    while temp:
      for i in temp:
        if grafo[i]:
          for j in grafo[i]:
            if j in temp:
              visitados.append(i)
              cola.append(i)
              temp.remove(i)
              break
          cont = cont + 1
          if cont>= len(temp) and i in temp:
            visitados.append(i)
            cola.append(i)
            temp.remove(i)
        else:
          cont = cont + 1
          if cont>= len(temp):
            visitados.append(i)
            cola.append(i)
            temp.remove(i)
          

In [3]:
# CASO 2

grafoBebidas2 = {
  "acai" : ["papaya"],
  "manzana" : ["papaya", "cereza", "acai"],
  "cereza" : [],
  "melon" : ["manzana", "cereza"],
  "papaya" : []
}

bfs(visitados, grafoBebidas2, "melon")  

melon manzana cereza papaya acai 

# ORDENAMIENTO TOPOLOGICO

In [39]:
from collections import defaultdict

def ordenamientoTopologico(G):
  nodoGrado = {}
  for nodo in G:
    nodoGrado[nodo] = 0
    
  cola = []

  for nodo in G:
    if(G[nodo]):
      for nodo_hijo in G[nodo]:
        nodoGrado[nodo_hijo] += 1

  for nodo in nodoGrado.keys():
    if nodoGrado[nodo] == 0:
      cola.append(nodo)

  ordenTopologicoFinal = []
  
  while cola:
    nodo = cola.pop()
    ordenTopologicoFinal.append(nodo)
    
    for nodo_hijo in G[nodo]:
      nodoGrado[nodo_hijo] -= 1
      
      if nodoGrado[nodo_hijo] == 0:
        cola.append(nodo_hijo)

  return ordenTopologicoFinal

In [40]:
# CASO 1

grafoBebidas1 = {
  "platano" : [],
  "acai" : ["platano"],
  "manzana" : ["acai"]
}

ordenamientoTopologico(grafoBebidas1)  

['manzana', 'acai', 'platano']

In [41]:
# CASO 2

grafoBebidas2 = {
  "acai" : ["papaya"],
  "manzana" : ["papaya", "cereza", "acai"],
  "cereza" : [],
  "melon" : ["manzana", "cereza"],
  "papaya" : []
}

ordenamientoTopologico(grafoBebidas2)  

['melon', 'manzana', 'acai', 'papaya', 'cereza']

In [42]:
# CASO 3

grafoBebidas3 = {
  "papaya" : [],
  "cereza" : ["papaya", "durazno"],
  "melon" : ["durazno", "capuli", "manzana"],
  "mango" : [],
  "cocona" : [],
  "acai" : ["cocona", "platano"],
  "platano" : ["mango"],
  "manzana" : ["cocona", "cereza", "mango"],
  "capuli" : [],
  "durazno" : [],
}

ordenamientoTopologico(grafoBebidas3)  

['acai',
 'platano',
 'melon',
 'manzana',
 'mango',
 'cereza',
 'durazno',
 'papaya',
 'cocona',
 'capuli']

## PARTE II
(8 puntos)

### ELECTIVA 1: Comprobar si un grafo está fuertemente conectado o no

Dado un grafo dirigido, comprueba si es fuertemente conexo o no. Se dice que un grafo dirigido es

fuertemente conexo si todos los vértices son accesibles desde todos los demás vértices.

Por ejemplo, el siguiente gráfico está fuertemente conectado ya que existe un camino entre todos los

pares de vértices:

Explique a través de un ejemplo utilizando los algoritmos: búsqueda primero en profundidad (DFS) o

una búsqueda primero en amplitud (BFS) y guárdelo como archivo Pregunta1.py



Datos de entrada del programa:

- Lista de aristas según el grafo

aristas = [(0, 4), (1, 0), (1, 2), (2, 1), (2, 4), (3, 1), (3, 2), (4, 3)]

- total de nodos en el grafo

n = 5

Salida del programa:

1 (si es fuertemente conectado SCC)

0 (si no lo es)






In [80]:
class Grafo:
    def __init__(self, aristas, n):
        self.listAdyacencia = [[] for x in range(n)]
 
        for (nodo1, nodo2) in aristas:
            self.listAdyacencia[nodo1].append(nodo2)


def DFS(grafo, nodo, visitado):
    visitado[nodo] = True
 
    for nodo_hijo in grafo.listAdyacencia[nodo]:
        if not visitado[nodo_hijo]:
            DFS(grafo, nodo_hijo, visitado)
 
 
def esFuertementeConectado(grafo, n):
    visitado = [False] * n
    nodo = 0                                            # el algoritmo empieza a partir de este nodo
    DFS(grafo, nodo, visitado)
 
    # Todos los nodos deben haber sido visitados del grafo original, sino no está fuertemente conectado
    for nodoTemp in visitado:
        if not nodoTemp: 
            return False
 
    visitado = [False] * n
 
    # Invertir la direccion de las aristas del grafo
    aristas = [(j, i) for i in range(n) for j in grafo.listAdyacencia[i]]
    gr = Grafo(aristas, n)
    DFS(gr, nodo, visitado)
 
    # Todos los nodos deben haber sido visitados del grafo invertido, sino no está fuertemente conectado
    for nodoTemp in visitado:
        if not nodoTemp:
            return False
 
    # si el graph es fuertemente conectado en ambos DFS
    return True
 
def main():
    aristas = [(0, 4), (1, 0), (1, 2), (2, 1), (2, 4), (3, 1), (3, 2), (4, 3)]
    n = 5                   
 
    grafo = Grafo(aristas, n)
 
    if esFuertementeConectado(grafo, n): print('(1) - El grafo esta fuertemente conectado')
    else: print('(0) - El grafo no esta fuertemente conectado')
        
main()

(1) - El grafo esta fuertemente conectado


### ELECTIVA 2: Encontrar el vértice raíz de un grafo

Un vértice raíz de un gráfico dirigido es un vértice u con un camino dirigido de **u** hacia **v**

para cada par de vértices (u, v) en el grafo. En otras palabras, todos los demás vértices del gráfico 

se pueden alcanzar desde el vértice raíz.

Un grafo puede tener múltiples vértices de raíz. Por ejemplo, cada vértice en un componente

fuertemente conectado es un vértice raíz. En tales casos, la solución debería devolver cualquiera de

ellos. Si el grafo no tiene vértices de raíz, la solución debería devolver -1. Presentar su solución en el

archivo Pregunta2.py

El vértice raíz es 4 porque tiene una ruta a cada otro vértice en el siguiente gráfico:

Datos de entrada del programa:

-  Lista de aristas del grafo

aristas = [(0, 1), (1, 2), (2, 3), (3, 0), (4, 3), (4, 5), (5, 0)]

-  Número total de nodos en el grafo (0 a 5)

n = 6

Salida del programa:

4

(-1 si no encuentra un nodo raíz).


In [37]:
class Grafo:
    def __init__(self, aristas, n):
        self.listAdyacencia = [[] for x in range(n)]
 
        for (nodo1, nodo2) in aristas:
            self.listAdyacencia[nodo1].append(nodo2)


def DFS(grafo, nodo, visitado):
    visitado[nodo] = True
 
    for nodo_hijo in grafo.listAdyacencia[nodo]:
        if not visitado[nodo_hijo]:
            DFS(grafo, nodo_hijo, visitado)
 
 
def encontrarVerticeRaiz(grafo, n):
    visitado = [False] * n
 
    nodo = 0
    for i in range(n):
        if not visitado[i]:
            DFS(grafo, i, visitado)
            nodo = i
 
    # resetear los vértices visitados
    for i in range(n):
        visitado[i] = False
 
    # Desde el ultimo nodo que se ha iniciado el DFS y era visitado (Este nodo es candidato a ser vertice raiz)
    # Verificar si este nodo esta conectado a todos los nodos del grafo
    DFS(grafo, nodo, visitado)
 
    for i in range(n):
        if not visitado[i]:
            return -1
 
    # nodo si es vertice raiz
    return nodo
 
 
def main():
    aristas = [(0, 1), (1, 2), (2, 3), (3, 0), (4, 3), (4, 5), (5, 0)]
    n = 6
 
    grafo = Grafo(aristas, n)
 
    root = encontrarVerticeRaiz(grafo, n)
 
    if root == -1: print('El vertice raiz no existe')
    else: print('El vertice raiz es: ', root)

main()
 

El vertice raiz es:  4


### Electiva 3: Encuentra el camino entre los vértices dados en un grafo dirigido

Dado un grafo dirigido y dos vértices (por ejemplo, vértice de origen y de destino), determine si el

vértice de destino es accesible desde el vértice de origen o no. Si existe una ruta desde el vértice de

origen hasta el vértice de destino, imprímala. Implemente su respuesta en Pregunta3.py

Por ejemplo, existen dos caminos [0—3—4—6—7] y [0—3—5—6—7] de vértice 0 a vértice 7 en el

siguiente grafo. Por el contrario, no hay camino desde el vértice 7 a ningún otro vértice.

Datos de entrada del programa:

- Lista de aristas del grafo

aristas = [ (0, 3), (1, 0), (1, 2), (1, 4), (2, 7), (3, 4), (3, 5), (4, 3), (4, 6), (5, 6), (6, 7)]

- Número total de nodos en el grafo (etiquetados de 0 a 7)

n = 8

nodo_inicial = 0

nodo_final = 7

Salida del programa:

1 (si existe un camino desde el nodo_inicial al nodo_final)

0 (si no existe un camino desde el nodo_inicial al nodo_final)

In [54]:
class Grafo:
    def __init__(self, aristas, n):
        self.listAdyacencia = [[] for x in range(n)]
 
        for (nodo1, nodo2) in aristas:
            self.listAdyacencia[nodo1].append(nodo2)
 
 
def isReachable(grafo, nodoOrigen, nodoDestino, visitado, camino):
    
    visitado[nodoOrigen] = True
    camino.append(nodoOrigen)
 
    # funcion parada: si se encuentra el vértice de destino
    if nodoOrigen == nodoDestino:
        return True

    # DFS
    for nodo_hijo in grafo.listAdyacencia[nodoOrigen]:
        
        if not visitado[nodo_hijo]:
            if isReachable(grafo, nodo_hijo, nodoDestino, visitado, camino):
                return True
 
    # eliminar el nodo actual
    camino.pop()
 
    # no existe camino entre nodoOrigen y nodoDestino
    return False
 
 
def main():
 
    edges = [ (0, 3), (1, 0), (1, 2), (1, 4), (2, 7), (3, 4),
              (3, 5), (4, 3), (4, 6), (5, 6), (6, 7) ]
    n = 8
    grafo = Grafo(edges, n)
    
    visitados = [False] * n
    nodoOrigen = 0
    nodoDestino = 7
 
    camino = []

    if isReachable(grafo, nodoOrigen, nodoDestino, visitados, camino):
        print(f'El camino desde el nodo {nodoOrigen} al nodo {nodoDestino}')
        print(f'El camino es: ', list(camino))
    else:
        print(f'No existe ningun camino que conecte el nodo {nodoOrigen} al {nodoDestino}')
        
main()

El camino desde el nodo 0 al nodo 7
El camino es:  [0, 3, 4, 6, 7]


### ALGORITMO KOSARAJU

In [6]:
from collections import defaultdict

class Grafo:

    def __init__(self, n):
        self.n = n
        self.grafo = defaultdict(list)

    def agregar_arista(self, nodo1, nodo2):
        self.grafo[nodo1].append(nodo2)

    def DFS(self, nodo, visitados):
        visitados[nodo] = True
        print(nodo, end=' ')
        
        for nodo_hijo in self.grafo[nodo]:
            if not visitados[nodo_hijo]:
                self.DFS(nodo_hijo, visitados)

    def usandoPila(self, nodo, visitados, pila):
        visitados[nodo] = True
        for nodo_hijo in self.grafo[nodo]:
            if not visitados[nodo_hijo]:
                self.usandoPila(nodo_hijo, visitados, pila)
        pila = pila.append(nodo)

    def invertirGrafo(self):
        grafoInvertido = Grafo(self.n)

        for i in self.grafo:
            for j in self.grafo[i]:
                grafoInvertido.agregar_arista(j, i)
        return grafoInvertido


    def kosaraju(self):
        pila = []
        visitados = [False] * (self.n)

        # Agregamos a la pila los nodos que conducen a un nodo ya visitado, y tambien sus nodos secundarios
        for i in range(self.n):
            if not visitados[i]:
                self.usandoPila(i, visitados, pila)

        grafoInvertido = self.invertirGrafo()

        visitados = [False] * (self.n)

        # Comienza desde el nodo superior de la pila y se aplica el DFS  para hallar todos sus nodos conectados
        # Se imprime el componente fuertemente conectado cuando alcance el nodo ya ha sido visitado
        while pila:
            nodoVisitado = pila.pop()
            if not visitados[nodoVisitado]:
                grafoInvertido.DFS(nodoVisitado, visitados)
                print("")


g = Grafo(8)
g.agregar_arista(0, 1)
g.agregar_arista(1, 2)
g.agregar_arista(2, 3)
g.agregar_arista(2, 4)
g.agregar_arista(3, 0)
g.agregar_arista(4, 5)
g.agregar_arista(5, 6)
g.agregar_arista(6, 4)
g.agregar_arista(6, 7)

print("Strongly Connected Components: ")
g.kosaraju()

Strongly Connected Components: 
0 3 2 1 
4 6 5 
7 


In [9]:
from collections import defaultdict

class Grafo:
    def __init__(self, aristas, n):
        self.listAdyacencia = [[] for x in range(n)]
 
        for (nodo1, nodo2) in aristas:
            self.listAdyacencia[nodo1].append(nodo2)
                
def DFS(grafo, nodo, visitado):
    visitado[nodo] = True
    print(nodo, end=' ')
    
    for nodo_hijo in grafo.listAdyacencia[nodo]:
        if not visitado[nodo_hijo]:
            DFS(grafo, nodo_hijo, visitado)

def usandoPila(grafo, nodo, visitados, pila):
    visitados[nodo] = True
    for nodo_hijo in grafo.listAdyacencia[nodo]:
        if not visitados[nodo_hijo]:
            usandoPila(grafo, nodo_hijo, visitados, pila)
    pila = pila.append(nodo)

def invertirGrafo(grafo, n):
    aristas = [(j, i) for i in range(n) for j in grafo.listAdyacencia[i]]
    
    grafoInvertido = Grafo(aristas, n)
    
    return grafoInvertido


def kosaraju(grafo, n):
    pila = []
    visitados = [False] * (n)

    # Agregamos a la pila los nodos que conducen a un nodo ya visitado, y tambien sus nodos secundarios
    for i in range(n):
        if not visitados[i]:
            usandoPila(grafo, i, visitados, pila)

    grafoInvertido = invertirGrafo(grafo, n)

    visitados = [False] * (n)

    # Comienza desde el nodo superior de la pila y se aplica el DFS  para hallar todos sus nodos conectados
    # Se imprime el componente fuertemente conectado cuando alcance el nodo ya ha sido visitado
    while pila:
        nodoVisitado = pila.pop()
        if not visitados[nodoVisitado]:
            DFS(grafoInvertido, nodoVisitado, visitados)
            print("")

def main():
    aristas = [(0, 1), (1, 2), (2, 3), (2, 4), (3, 0), (4, 5), (5, 6), (6, 4), (6, 7)]
    n = 8        

    grafo = Grafo(aristas, n)

    print("Strongly Connected Components:")
    kosaraju(grafo, n)
    
main()

Strongly Connected Components:
0 3 2 1 
4 6 5 
7 


### Tamanos de las CFC

Escriba una funcion que calculer los tamanos (numero de nodos) de las CFC. Escriba una funcion

que calcula el numero de CFC de talla i y que la muestra.

Ejemplo del resultado:

Hay 389 nodos isolados

Hay 50 CFC de tamano 2

Hay 11 CFC de tamano 3

Hay 6 CFC de tamano 4

Hay 1 CFC de tamano 4447

In [28]:
from collections import defaultdict

class Grafo:
    def __init__(self, aristas, n):
        self.listAdyacencia = [[] for x in range(n)]
 
        for (nodo1, nodo2) in aristas:
            self.listAdyacencia[nodo1].append(nodo2)
                
def DFS(grafo, nodo, visitado, lsttamannoCFC):
    
    visitado[nodo] = True
    print(nodo, end=' ')
    lsttamannoCFC.append(nodo)
    
    for nodo_hijo in grafo.listAdyacencia[nodo]:
        if not visitado[nodo_hijo]:
            DFS(grafo, nodo_hijo, visitado, lsttamannoCFC)
    
    return lsttamannoCFC

def usandoPila(grafo, nodo, visitados, pila):
    visitados[nodo] = True
    for nodo_hijo in grafo.listAdyacencia[nodo]:
        if not visitados[nodo_hijo]:
            usandoPila(grafo, nodo_hijo, visitados, pila)
    pila = pila.append(nodo)

def invertirGrafo(grafo, n):
    aristas = [(j, i) for i in range(n) for j in grafo.listAdyacencia[i]]
    
    grafoInvertido = Grafo(aristas, n)
    
    return grafoInvertido


def tamannoCFC(grafo, n):
    pila = []
    visitados = [False] * (n)

    # Agregamos a la pila los nodos que conducen a un nodo ya visitado, y tambien sus nodos secundarios
    for i in range(n):
        if not visitados[i]:
            usandoPila(grafo, i, visitados, pila)

    grafoInvertido = invertirGrafo(grafo, n)

    visitados = [False] * (n)
    tamanos = {}
    # Comienza desde el nodo superior de la pila y se aplica el DFS  para hallar todos sus nodos conectados
    # Se imprime el componente fuertemente conectado cuando alcance el nodo ya ha sido visitado
    while pila:
        nodoVisitado = pila.pop()
        lst = []
        if not visitados[nodoVisitado]:
            lsttamanosCFC = DFS(grafoInvertido, nodoVisitado, visitados, lst)
            key = len(lsttamanosCFC)
            if key in tamanos:
                tamanos[key] = tamanos[key] + 1
            else:
                tamanos[key] = 1
            
            print("")
    
    print("\nTamannos (numero de nodos) de las Componentes Fuertemente conexas: ")
    for i in tamanos:
        if(i==1):
            print(f"Hay {tamanos[i]} nodo(s) isolado(s) de tamano {i}")
        else:
            print(f"Hay {tamanos[i]} CFC de tamano {i}")

def main():
    aristas = [(0, 1), (1, 2), (2, 3), (2, 4), (3, 0), (4, 5), (5, 6), (6, 4), (6, 7)]
    n = 8        

    grafo = Grafo(aristas, n)

    print("Compenentes Fuertemente Conexas: ")
    tamannoCFC(grafo, n)
    
    
main()

Compenentes Fuertemente Conexas: 
0 3 2 1 
4 6 5 
7 

Tamannos (numero de nodos) de las Componentes Fuertemente conexas: 
Hay 1 CFC de tamano 4
Hay 1 CFC de tamano 3
Hay 1 nodo(s) isolado(s) de tamano 1


# ALGORITMO A STAR

In [36]:
from collections import deque

class Grafo:
    def __init__(self, lista_adyacencia):
        self.lista_adyacencia = lista_adyacencia

    def get_nodosAdyacentes(self, nodo):
        return self.lista_adyacencia[nodo]

    def heuristica(self, n):
        H = {
            'A': 0,
            'B': 1,
            'C': 1,
            'D': 1
        }

        return H[n]

def a_star(grafo, nodoOrigen, nodoDestino):
    nodos_a_evaluar = set([nodoOrigen])
    visitados = set([])

    costos = {}
    costos[nodoOrigen] = 0

    previo = {}
    previo[nodoOrigen] = nodoOrigen

    while len(nodos_a_evaluar) > 0:
        nodo = None

        # ENCONTRAR EL NODO CON EL MENOR COSTO TOTAL = PESO ARISTA + HEURISTICA
        for nodoEvaluado in nodos_a_evaluar:
                
            if nodo == None or (costos[nodoEvaluado] + grafo.heuristica(nodoEvaluado) < costos[nodo] + grafo.heuristica(nodo)):
                nodo = nodoEvaluado;
            
        # funcion parada: si no hay caminos
        if nodo == None:
            print("No existe ningun camino")
            return None

        # funcion parada: si el nodo actual es el nodoDestino
        if nodo == nodoDestino:
            camino = []

            while previo[nodo] != nodo:
                camino.append(nodo)
                nodo = previo[nodo]

            camino.append(nodoOrigen)
            camino.reverse()
            
            print("Costo del camino: \n")
            costoTotal = 0
            for i in costos: 
                if(i in camino and i != nodoOrigen): 
                    costoViaje = (costos[i] + grafo.heuristica(i)) - costos[previo[i]]
                    costoTotal = costoTotal + costoViaje
                    print(f"Costo del nodo '{previo[i]}' al nodo '{i}' =  {costoViaje}")
            
            print(f"\nCosto total del camino: {costoTotal}")
            print("\nCamino encontrado: ")
            return camino

        # ALGORITMO PARA LOS NODOS ADYACENTES DEL NODO ACTUAL
        for (nodo2, pesoArista) in grafo.get_nodosAdyacentes(nodo):
            if nodo2 not in nodos_a_evaluar and nodo2 not in visitados:
                nodos_a_evaluar.add(nodo2)
                previo[nodo2] = nodo
                costos[nodo2] = costos[nodo] + pesoArista
            else:
                if costos[nodo2] > costos[nodo] + pesoArista:
                    costos[nodo2] = costos[nodo] + pesoArista
                    previo[nodo2] = nodo

                    if nodo2 in visitados:
                        visitados.remove(nodo2)
                        nodos_a_evaluar.add(nodo2)

        # TODOS LOS NODOS ADYACENTES DEL NODO ACTUAL YA HAN SIDO VISITADOS
        nodos_a_evaluar.remove(nodo)
        visitados.add(nodo)

    print('No existe ningun camino')
    return None


In [37]:
lista_adyacencia = {
    'A': [('B', 1), ('C', 3), ('D', 7)],
    'B': [('D', 5)],
    'C': [('D', 12)]
}
grafo = Grafo(lista_adyacencia)

a_star(grafo, 'A', 'D')

Costo del camino: 

Costo del nodo 'A' al nodo 'B' =  2
Costo del nodo 'B' al nodo 'D' =  6

Costo total del camino: 8

Camino encontrado: 


['A', 'B', 'D']

# ALGORITMO DIJIKSTRA

- CAMINO MAS CORTO QUE ESTE CONECTADO A TODOS LOS NODOS A PARTIR DE UN NODO ORIGEN

- CAMINO MAS CORTO ENTRE DOS NODOS

In [144]:
def dijkstraGrafoDirigido(Grafo, nodoOrigen):
    n = len(Grafo)
    costos, camino, visitado = {}, {}, {}
    result = []

    for nodo in Grafo:
        costos[nodo] = math.inf
        camino[nodo] = -1
        visitado[nodo] = False
        
    cola = [nodo for nodo in Grafo]
    costos[nodoOrigen] = 0

    while cola:
        nodo = min(cola, key=costos.get)
        cola.remove(nodo)
        result.append(nodo)
        
        if not visitado[nodo]:
            visitado[nodo] = True
            
            for nodo_adyacente in Grafo[nodo]:
                costoNuevo = costos[nodo] + Grafo[nodo][nodo_adyacente]
        
                if  costos[nodo_adyacente] > costoNuevo:
                    costos[nodo_adyacente] = costoNuevo
                    camino[nodo_adyacente] = nodo

    return result, costos, camino

In [151]:
grafoPrueba = {
    'a': {'b': 4, 'c': 3},
    'b': {'d': 5},
    'c': {'b': 2, 'd': 3, 'e': 6},
    'd': {'f': 5, 'e': 1},
    'e': {'g': 5},
    'g': {'z': 4},
    'f': {'g': 2, 'z': 7},
    'z': {}
}



### El camino mas corto desde el nodoOrigen a todos los nodos del Grafo

nodoOrigen = 'c'
nodos, distancia, camino = dijkstraGrafoDirigido(grafoPrueba, nodoOrigen)
print(f"\nnodos = {nodos}")
print(f"\ndistancia desde el nodo '{nodoOrigen}' al nodo = {distancia}")
#print(f"camino = {camino}")

print("\ncaminos: \n")
for nodo in camino:
    if(camino[nodo] != -1):
        print(f"'{camino[nodo]}' -> '{nodo}'")
        
        
        
## El camino camino mas corto entre 2 nodos:

nodoDestino = 'e'
print(f"\nLa distancia mas corto entre el nodo '{nodoOrigen}' y el nodo '{nodoDestino}' es {distancia[nodoDestino]}")
        



nodos = ['c', 'b', 'd', 'e', 'f', 'g', 'z', 'a']

distancia desde el nodo 'c' al nodo = {'a': inf, 'b': 2, 'c': 0, 'd': 3, 'e': 4, 'g': 9, 'f': 8, 'z': 13}

caminos: 

'c' -> 'b'
'c' -> 'd'
'd' -> 'e'
'e' -> 'g'
'd' -> 'f'
'g' -> 'z'

La distancia mas corta entre el nodo 'c' y el nodo 'e' es 4


#### 1. MATRIZ

In [74]:
def dijkstraMatriz(G, nodoOrigen):
  n = len(G)
  visitado = [False]*n
  camino = [-1]*n
  costos = [math.inf]*n

  costos[nodoOrigen] = 0
  pqueue = [(0, nodoOrigen)]
  while pqueue:
    costoActual, nodo1 = hq.heappop(pqueue)
    
    if not visitado[nodo1]:
      visitado[nodo1] = True
      
      for nodo2 in range(n):
        if G[nodo1, nodo2] > 0 and not visitado[nodo2]:
          costoNuevo = costoActual + G[nodo1, nodo2]
          
          if costoNuevo < costos[nodo2]:
            costos[nodo2] = costoNuevo
            camino[nodo2] = nodo1
            
            hq.heappush(pqueue, (costoNuevo, nodo2))

  return camino, costos

LEER ARCHIVO Y PASARLO A MATRIX

In [35]:
%%file 0501.am
0 2 0 2 9 0 0 0
2 0 1 2 0 2 0 0
0 1 0 0 2 0 2 0
2 2 0 0 0 9 0 3
9 0 2 0 0 0 0 8
0 2 0 9 0 0 7 0
0 0 2 0 0 7 0 3
0 0 0 3 8 0 3 0

Writing 0501.am


In [56]:
GrafoDijikstraMatriz = np.loadtxt("0501.am")
print(GrafoDijikstraMatriz)

[[0. 2. 0. 2. 9. 0. 0. 0.]
 [2. 0. 1. 2. 0. 2. 0. 0.]
 [0. 1. 0. 0. 2. 0. 2. 0.]
 [2. 2. 0. 0. 0. 9. 0. 3.]
 [9. 0. 2. 0. 0. 0. 0. 8.]
 [0. 2. 0. 9. 0. 0. 7. 0.]
 [0. 0. 2. 0. 0. 7. 0. 3.]
 [0. 0. 0. 3. 8. 0. 3. 0.]]


In [75]:
camino, coste = dijkstraMatriz(GrafoDijikstraMatriz, 3)
print(camino)
print(coste)

[3, 3, 1, -1, 2, 1, 2, 3]
[2.0, 2.0, 3.0, 0, 5.0, 4.0, 5.0, 3.0]


#### 2. LISTA DE ADYACENCIA

In [33]:
def dijkstraListaAdyacencia(G, nodoOrigen):
  n = len(G)
  visitados = [False]*n
  camino = [-1]*n
  costo = [math.inf]*n

  costo[nodoOrigen] = 0
  pqueue = [(0, nodoOrigen)]
  
  while pqueue:
    costoActual, nodo = hq.heappop(pqueue)
    
    if not visitados[nodo]:
      visitados[nodo] = True
      
      for nodo1, nodo2 in G[nodo]:
        if not visitados[nodo1]:
          costoNuevo = costoActual + nodo2
          
          if costoNuevo < costo[nodo1]:
            costo[nodo1] = costoNuevo
            camino[nodo1] = nodo
            hq.heappush(pqueue, (costoNuevo, nodo1))

  return camino, costo

LEER ARCHIVO Y PASARLO A LISTA DE ADYACENCIA

In [1]:
%%file 0502.al
1 2 3 2 4 9
0 2 2 1 3 2 5 2
1 1 4 2 6 2
0 2 1 2 5 9 7 3
0 9 2 2 7 8
1 2 3 9 6 7
2 2 5 7 7 3
3 3 4 8 6 3

Writing 0502.al


In [3]:
with open("0502.al") as fileListaAdyacencia:
  GrafoLA = []
  
  for linea in fileListaAdyacencia:
    lista = [int(x) for x in linea.split()]
    GrafoLA.append([])
    
    for i in range(0, len(lista), 2):
      GrafoLA[-1].append((lista[i], lista[i+1]))

for arista in GrafoLA:
  print(arista)


[(1, 2), (3, 2), (4, 9)]
[(0, 2), (2, 1), (3, 2), (5, 2)]
[(1, 1), (4, 2), (6, 2)]
[(0, 2), (1, 2), (5, 9), (7, 3)]
[(0, 9), (2, 2), (7, 8)]
[(1, 2), (3, 9), (6, 7)]
[(2, 2), (5, 7), (7, 3)]
[(3, 3), (4, 8), (6, 3)]


In [34]:
path, cost = dijkstraListaAdyacencia(GrafoLA, 3)
print(path)
print(cost)

[3, 3, 1, -1, 2, 1, 2, 3]
[2, 2, 3, 0, 5, 4, 5, 3]


### ESCRIBIR ARCHIVOS TEXTO

In [38]:
## ARISTAS
%%file lorem.txt
1 2
1 4
2 5
3 4
3 5

Writing lorem.txt


In [15]:
%%file matrizFile.txt
1 0 1
1 1 1
1 0 1

Overwriting matrizFile.txt


### LEER ARCHIVOS TEXTO

In [56]:
## ARISTAS

with open("lorem.txt") as fileListaAdyacencia:
  GrafoLA = defaultdict(list)
  
  for linea in fileListaAdyacencia:
    lista = [int(x) for x in linea.split()]
    
    for i in range(0, len(lista), 2):
      GrafoLA[lista[i]].append(lista[i+1])
      
### DICCIONARIO DE LISTAS - LISTA DE ADYACENCIA
for nodo in GrafoLA:
  print(f"{nodo}: {GrafoLA[nodo]}")

1: [2, 4]
2: [5]
3: [4, 5]


In [44]:
import numpy as np

## MATRIZ
m = np.loadtxt("matrizFile.txt", dtype = int)
print(m, "\n")

## ENTENDIENDO LOS DATOS DE LA MATRIZ
conti = 0;
for i in m:
    contj=0
    for j in i:
        print(f"Arista entre el nodo {conti} y el nodo {contj} es de peso: {j}")
        contj+=1
    conti+=1

## AGREGANDOLOS A UNA LISTA DE ADYACENCIA
print("\nlista de adyacencia sin peso en las aristas")
lista_adyacencia = defaultdict(list)

conti = 0;
for i in m:
    contj=0
    for j in i:
        if(j==1): lista_adyacencia[conti].append(contj)
        contj+=1
    conti+=1

for nodo in lista_adyacencia:
    print(f"{nodo}: {lista_adyacencia[nodo]}")

## AGREGANDOLOS A UNA LISTA DE ADYACENCIA CON PESO EN LAS ARISTASSSSS
print("\nlista de adyacencia con peso en las aristas")

lista_adyacencia2 = defaultdict(list)

conti = 0;
for i in m:
    contj=0
    for j in i:
        if(j==1): 
            aristaYpeso={}
            aristaYpeso[contj] = j
            lista_adyacencia2[conti].append(aristaYpeso)
        contj+=1
    conti+=1

for nodo in lista_adyacencia:
    print(f"{nodo}: {lista_adyacencia2[nodo]}")

[[1 0 1]
 [1 1 1]
 [1 0 1]] 

Arista entre el nodo 0 y el nodo 0 es de peso: 1
Arista entre el nodo 0 y el nodo 1 es de peso: 0
Arista entre el nodo 0 y el nodo 2 es de peso: 1
Arista entre el nodo 1 y el nodo 0 es de peso: 1
Arista entre el nodo 1 y el nodo 1 es de peso: 1
Arista entre el nodo 1 y el nodo 2 es de peso: 1
Arista entre el nodo 2 y el nodo 0 es de peso: 1
Arista entre el nodo 2 y el nodo 1 es de peso: 0
Arista entre el nodo 2 y el nodo 2 es de peso: 1

lista de adyacencia sin peso en las aristas
0: [0, 2]
1: [0, 1, 2]
2: [0, 2]

lista de adyacencia con peso en las aristas
0: [{0: 1}, {2: 1}]
1: [{0: 1}, {1: 1}, {2: 1}]
2: [{0: 1}, {2: 1}]


In [49]:
from collections import defaultdict
mi_dict = defaultdict(list)
dicArista = {}
dicArista2 = {}
dicArista['B'] =2 
dicArista2['C'] =4 
mi_dict["A"].append(dicArista)
mi_dict["A"].append(dicArista2)


print(mi_dict)

defaultdict(<class 'list'>, {'A': [{'B': 2}, {'C': 4}]})
